# Generated by Django 3.2.5 on 2021-07-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Ижевск', max_length=20, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.CharField(max_length=4, verbose_name='Дом')),
                ('entrance', models.CharField(default=1, max_length=2, verbose_name='Подъезд')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateField(verbose_name='Дата создания')),
            ],
        ),
    ]
