# Generated by Django 3.2.5 on 2021-07-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elevators',
            options={'verbose_name': 'Лифт', 'verbose_name_plural': 'Лифты'},
        ),
        migrations.AddField(
            model_name='elevators',
            name='comunication_type',
            field=models.CharField(default='Обь', max_length=50, verbose_name='Тип связи'),
        ),
        migrations.AlterField(
            model_name='elevators',
            name='house',
            field=models.CharField(default=6, max_length=4, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='elevators',
            name='street',
            field=models.CharField(default='Союзная', max_length=50, verbose_name='Улица'),
        ),
    ]
