# Generated by Django 3.2.5 on 2021-07-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210706_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevators',
            name='station_type',
            field=models.CharField(default='УЛ', max_length=50, verbose_name='Станция'),
        ),
        migrations.AlterField(
            model_name='elevators',
            name='comment',
            field=models.TextField(default='Пример: 10.11.12.13. Точка ростелеком Берша 54 второй подъезд, воздушка с первого(Берша 54) на пятый подъезд(Берша 32), перемычки между подъездами по тех.этажу, ключи на союзной, 123', verbose_name='Комментарий'),
        ),
    ]
