# Generated by Django 3.2.5 on 2021-07-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210706_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevators',
            old_name='comunication_type',
            new_name='communication_type',
        ),
        migrations.AddField(
            model_name='elevators',
            name='elevator',
            field=models.CharField(default='груз/пасс', max_length=50, verbose_name='Лифт №'),
        ),
    ]
