# Generated by Django 3.2.5 on 2021-07-07 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210706_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevators',
            name='date',
        ),
        migrations.AddField(
            model_name='elevators',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elevators',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='elevators',
            name='station_type',
            field=models.CharField(default='нет данных', max_length=50, verbose_name='Станция'),
        ),
    ]
