# Generated by Django 3.2.5 on 2021-07-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210707_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevators',
            name='city',
            field=models.CharField(default='ИЖЕВСК', max_length=20, verbose_name='Город'),
        ),
    ]
