# Generated by Django 3.2.5 on 2021-07-12 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_elevators_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevators',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='elevators',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='elevators',
            name='house',
        ),
        migrations.RemoveField(
            model_name='elevators',
            name='street',
        ),
        migrations.AddField(
            model_name='elevators',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
