# Generated by Django 3.2.5 on 2021-07-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_elevators_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevators',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
    ]
