# Generated by Django 3.2.5 on 2021-07-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_elevators_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevators',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
