# Generated by Django 3.2.5 on 2021-07-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_elevators_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevators',
            name='communication_type',
            field=models.CharField(max_length=255, verbose_name='Тип связи'),
        ),
        migrations.AlterField(
            model_name='elevators',
            name='station_type',
            field=models.CharField(default='нет данных', max_length=255, verbose_name='Станция'),
        ),
    ]
