# Generated by Django 3.2.5 on 2021-07-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_elevators_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevators',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
